import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowDown, Award, Code2, ExternalLink, Github, GraduationCap, Linkedin, Mail, MapPin, Menu, Send, X } from 'lucide-react'
import SectionTitle from './components/SectionTitle'
import ThemeToggle from './components/ThemeToggle'
import ProjectCard from './components/ProjectCard'
import { certifications, projects, skills } from './data/portfolio'

const nav = ['Home', 'About', 'Skills', 'Projects', 'Education', 'Certifications', 'Contact']

export default function App() {
  const [dark, setDark] = useState(() => localStorage.theme === 'dark' || (!localStorage.theme && matchMedia('(prefers-color-scheme: dark)').matches))
  const [menuOpen, setMenuOpen] = useState(false)
  const [formStatus, setFormStatus] = useState('')
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.theme = dark ? 'dark' : 'light' }, [dark])
  const go = (name) => { setMenuOpen(false); document.getElementById(name.toLowerCase())?.scrollIntoView({ behavior: 'smooth' }) }

  return <main className="overflow-x-hidden bg-mist text-ink transition-colors dark:bg-midnight">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-mist/85 backdrop-blur-md dark:border-slate-800 dark:bg-midnight/85">
      <div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8">
        <button onClick={() => go('Home')} className="font-display text-xl font-bold tracking-tight dark:text-white">Aime<span className="text-ocean dark:text-teal-400">.</span></button>
        <nav className="hidden items-center gap-5 lg:flex">{nav.slice(1).map(item => <button key={item} onClick={() => go(item)} className="text-xs font-semibold text-slate-600 transition hover:text-ocean dark:text-slate-300 dark:hover:text-teal-300">{item}</button>)}</nav>
        <div className="flex items-center gap-3"><ThemeToggle isDark={dark} toggle={() => setDark(!dark)} /><button onClick={() => setMenuOpen(!menuOpen)} className="grid h-10 w-10 place-items-center rounded-full border border-slate-200 text-slate-700 lg:hidden dark:border-slate-700 dark:text-white">{menuOpen ? <X size={19}/> : <Menu size={20}/>}</button></div>
      </div>
      <AnimatePresence>{menuOpen && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="border-t border-slate-200 bg-mist px-5 py-5 lg:hidden dark:border-slate-800 dark:bg-midnight">{nav.slice(1).map(item => <button key={item} onClick={() => go(item)} className="block w-full py-3 text-left text-sm font-semibold dark:text-white">{item}</button>)}</motion.div>}</AnimatePresence>
    </header>

    <section id="home" className="grain relative isolate overflow-hidden bg-[#edf5f4] pt-24 dark:bg-[#121212]">
      <div className="absolute -right-32 top-24 -z-10 h-[540px] w-[540px] rounded-full bg-[#308280]/15 blur-3xl" />
      <div className="mx-auto grid min-h-[calc(100vh-6rem)] max-w-7xl items-center gap-10 px-5 py-10 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-14">
        <motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}>
          <p className="text-sm text-slate-500 dark:text-slate-400">Hi! I am</p><p className="mt-1 text-base font-semibold text-slate-700 dark:text-slate-200">Byiringiro Ingabire Aime</p>
          <h1 className="mt-4 max-w-3xl text-5xl font-extrabold leading-[1.02] tracking-tight text-ocean sm:text-6xl xl:text-7xl">Software Developer</h1>
          <p className="mt-6 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-300">A Computer Science student crafting reliable web and backend solutions, while exploring AI, data, networking, and cloud computing.</p>
          <div className="mt-8 flex flex-wrap gap-3"><button onClick={() => go('Contact')} className="inline-flex items-center gap-2 rounded-md bg-ocean px-6 py-3 text-sm font-bold text-white shadow-lg shadow-[#308280]/20 transition hover:bg-[#256a68]">Hire me <ArrowDown size={16}/></button><button onClick={() => go('Projects')} className="rounded-md border border-slate-300 px-6 py-3 text-sm font-bold text-slate-700 transition hover:border-ocean hover:text-ocean dark:border-slate-600 dark:text-slate-100">View projects</button></div>
          <div className="mt-10 grid max-w-md grid-cols-3 divide-x divide-slate-300 rounded-md bg-white/80 px-3 py-4 shadow-sm dark:divide-slate-700 dark:bg-white/5"><MiniStat value="6+" label="Projects"/><MiniStat value="2027" label="Graduation"/><MiniStat value="7" label="Skill areas"/></div>
        </motion.div>
        <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .7, delay: .1 }} className="relative mx-auto w-full max-w-md">
          <div className="absolute inset-3 rounded-full bg-[#308280]/10 dark:bg-white/5"/><div className="relative aspect-[4/5] overflow-hidden rounded-b-[10rem] rounded-t-[10rem] bg-slate-200 shadow-2xl shadow-slate-900/20"><img src="/images/aime-portrait.jpeg" alt="Byiringiro Ingabire Aime in a suit" className="h-full w-full object-cover object-top"/></div>
          <div className="absolute -bottom-3 -left-3 rounded-md border border-white/70 bg-white/90 px-4 py-3 shadow-lg backdrop-blur dark:border-slate-700 dark:bg-slate-900/90"><p className="font-mono text-[10px] uppercase tracking-wider text-ocean">Currently studying</p><p className="mt-1 text-sm font-bold dark:text-white">Information Technology @ AUCA</p></div>
        </motion.div>
      </div>
    </section>

    <section id="about" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:py-32"><SectionTitle eyebrow="01 / About" title="Curious by nature. Grounded in systems."/><div className="space-y-6 text-lg leading-8 text-slate-600 dark:text-slate-300"><p>I am a Networks and Communication Systems student in the Faculty of Information Technology at the Adventist University of Central Africa, expected to graduate in 2027.</p><p>I enjoy turning complex problems into useful, reliable experiences—from user-facing web interfaces and backend APIs to data, networking, and cloud systems.</p><div className="grid grid-cols-2 gap-4 pt-5"><Stat number="2027" label="Expected graduation"/><Stat number="7" label="Technical focus areas"/></div></div></section>

    <section id="skills" className="bg-white py-24 dark:bg-slate-950 lg:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionTitle eyebrow="02 / Skills" title="A practical, expanding toolkit." text="A foundation across software engineering disciplines, with a focus on learning by building."/><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{skills.map(([category, items], index) => <motion.div initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .04 }} key={category} className="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><Code2 className="text-ocean dark:text-teal-400" size={19}/><h3 className="mt-6 font-bold dark:text-white">{category}</h3><div className="mt-4 flex flex-wrap gap-2">{items.map(item => <span className="rounded-md bg-slate-100 px-2.5 py-1.5 text-xs font-semibold text-slate-600 dark:bg-slate-900 dark:text-slate-300" key={item}>{item}</span>)}</div></motion.div>)}</div></div></section>

    <section id="projects" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><SectionTitle eyebrow="03 / Selected projects" title="Things I’ve been building."/><p className="max-w-xs text-sm leading-6 text-slate-500 dark:text-slate-400">Each project represents a different problem space and an opportunity to learn in public.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map(project => <ProjectCard key={project.title} project={project}/>)}</div></section>

    <section id="education" className="bg-midnight py-24 text-white lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-2"><SectionTitle light eyebrow="04 / Education" title="Learning the fundamentals, then applying them."/><div className="rounded-3xl border border-slate-700 bg-slate-900/70 p-8"><GraduationCap className="text-teal-300" size={28}/><p className="mt-8 font-mono text-xs uppercase tracking-[.17em] text-teal-300">2023 — 2027 (expected)</p><h3 className="mt-3 text-2xl font-bold">Bachelor’s in Computer Science</h3><p className="mt-3 text-slate-300">Adventist University of Central Africa (AUCA)</p><div className="mt-8 border-t border-slate-700 pt-5 text-sm text-slate-400">Developing foundations in programming, software development, databases, networks, and computing systems.</div></div></div></section>

    <section id="certifications" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><SectionTitle eyebrow="05 / Certifications" title="Credentials & continued learning." text="Professional learning across software development, networking, cloud, and cybersecurity."/><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{certifications.map(cert => <a href={cert.file} target="_blank" rel="noreferrer" className="group rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-1 hover:border-ocean hover:shadow-lg dark:border-slate-800 dark:bg-slate-900 dark:hover:border-teal-400" key={cert.title}><Award size={20} className="text-ocean dark:text-teal-400"/><p className="mt-8 text-sm font-bold dark:text-white">{cert.title}</p><p className="mt-2 text-xs text-slate-500 dark:text-slate-400">{cert.issuer}</p><p className="mt-5 font-mono text-[10px] uppercase tracking-wider text-slate-400">{cert.date}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-ocean dark:text-teal-400">View certificate <ExternalLink size={13}/></span></a>)}</div></section>

    <section id="contact" className="px-5 pb-8 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 rounded-[2rem] bg-ocean px-6 py-14 text-white sm:px-12 lg:grid-cols-[.8fr_1.2fr] lg:px-16 lg:py-20"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-teal-100">06 / Contact</p><h2 className="mt-4 text-4xl font-extrabold leading-tight sm:text-5xl">Let’s work together.</h2><p className="mt-5 max-w-md leading-7 text-teal-50">Send a message with your idea, question, or opportunity. It will be delivered directly to my inbox.</p><a href="mailto:aimebyiringiro123@gmail.com" className="mt-4 inline-block text-sm font-semibold underline underline-offset-4">aimebyiringiro123@gmail.com</a><div className="mt-8 flex gap-3"><Social icon={Github} href="https://github.com/aimebyiringiro123" label="GitHub"/><Social icon={Linkedin} href="https://www.linkedin.com/in/byiringiro-ingabire-aime-9a589a2b3/" label="LinkedIn"/><Social icon={Mail} href="mailto:aimebyiringiro123@gmail.com" label="Email"/></div></div><><form action="https://formsubmit.co/aimebyiringiro123@gmail.com" method="POST" target="formsubmit-frame" onSubmit={(event) => { const form = event.currentTarget; setFormStatus('Thanks! Your message has been sent.'); window.setTimeout(() => form.reset(), 0) }} className="grid gap-4 rounded-2xl bg-white p-5 text-ink shadow-xl sm:grid-cols-2 sm:p-7"><input type="hidden" name="_subject" value="New portfolio contact message" /><input type="hidden" name="_template" value="table" /><input type="hidden" name="_captcha" value="false" /><label className="text-sm font-bold">Your name<input required name="name" placeholder="Your name" className="mt-2 w-full rounded-md border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none transition focus:border-ocean focus:ring-2 focus:ring-ocean/20" /></label><label className="text-sm font-bold">Email address<input required type="email" name="email" placeholder="you@email.com" className="mt-2 w-full rounded-md border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none transition focus:border-ocean focus:ring-2 focus:ring-ocean/20" /></label><label className="text-sm font-bold sm:col-span-2">Message<textarea required name="message" rows="4" placeholder="Tell me about your project..." className="mt-2 w-full resize-none rounded-md border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none transition focus:border-ocean focus:ring-2 focus:ring-ocean/20" /></label><button className="inline-flex w-fit items-center gap-2 rounded-md bg-ocean px-5 py-3 text-sm font-bold text-white transition hover:bg-[#256a68] sm:col-span-2">Send message <Send size={16}/></button>{formStatus && <p aria-live="polite" className="text-sm font-semibold text-emerald-700 sm:col-span-2">{formStatus}</p>}</form><iframe name="formsubmit-frame" title="Contact form submission" className="hidden" /></></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-7 text-xs text-slate-500 sm:flex-row sm:justify-between sm:px-8 dark:text-slate-400"><span>© {new Date().getFullYear()} Byiringiro Ingabire Aime</span><span className="inline-flex items-center gap-1"><MapPin size={12}/> Rwanda</span></footer>
  </main>
}

function Stat({ number, label }) { return <div className="rounded-2xl bg-white p-5 dark:bg-slate-900"><p className="font-display text-3xl font-semibold text-ocean dark:text-teal-400">{number}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{label}</p></div> }
function MiniStat({ value, label }) { return <div className="px-3 first:pl-1"><p className="text-sm font-extrabold text-ocean dark:text-teal-300">{value}</p><p className="mt-1 text-[10px] font-semibold text-slate-500 dark:text-slate-400">{label}</p></div> }
function Social({ icon: Icon, href, label }) { return <a href={href} target={href?.startsWith('http') ? '_blank' : undefined} rel="noreferrer" aria-label={label} className="grid h-9 w-9 place-items-center rounded-full border border-teal-300/50 transition hover:bg-white hover:text-ocean"><Icon size={16}/></a> }
